name: fit_track_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^27.2.3
  pedometer: ^4.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.270
  http: ^1.3.0
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/static/

flutter_intl:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/static/
